version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - '3306:3306'
    networks:
      - camp2
networks:
  camp2:
